/*
 * SimpleGLCanvas.java
 *
 * Created on 30. Juli 2008, 16:18
 */

package org.RobotGUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.GLJPanel;
import matlabcontrol.*;
import com.sun.opengl.util.Animator;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.GLCanvas;
import javax.media.opengl.GLCapabilities;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
/**
 *
 * @author cylab
 * @author mbien
 */
public class RobotGUI extends JFrame {
    private RemoteMatlabProxy proxy;
    private double cancelOrAVal;
    private double cancelOrBVal;
    Delegator delegator;

    static {
        // When using a GLCanvas, we have to set the Popup-Menues to be HeavyWeight,
        // so they display properly on top of the GLCanvas
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);
        System.out.println(System.getProperty("java.library.path"));
    }
    
    private Animator animator;
    private Renderer render;
    private JFrame frame;
    private GLCanvas canvas1;
    private GLCanvas canvas2;
    private GLCanvas canvas3;
    private GLCanvas canvas4;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel angleA;
    private JLabel angleB;
    private JButton cancelOr;
    private JButton connect;
    private JLabel currentAngleAOr;
    private JLabel currentAngleBOr;
    private JLabel currentAngleOrALabel;
    private JLabel currentAngleOrBLabel;
    private JButton decrAngleA;
    private JButton decrAngleB;
    private JButton depthDecrFull;
    private JButton depthDecrPart;
    private JButton depthIncrFull;
    private JButton depthIncrPart;
    private JLabel depthLabel;
    private JLabel dirVectorLabel;
    private JTextField dirX;
    private JTextField dirY;
    private JTextField dirZ;
    private JButton execOr;
    private JButton extract;
    private JLabel header;
    private JButton incrAngleA;
    private JButton incrAngleB;
    private JButton initialize;
    private JButton insert;
    private JButton insertCancel;
    private JScrollPane jScrollPane1;
    private JTextArea messageCenter;
    private JLabel messageCenterLabel;
    private JButton move;
    private JButton pause;
    private JLabel posVectorLabel;
    private JTextField posX;
    private JTextField posY;
    private JTextField posZ;
    private GLCanvas robotDisplay;
    private JButton selectPath;
    private JButton stop;
    
    private JButton setAngles;
    private JTextField i;
    private JLabel angles;
    private JLabel value;
    private JTextField v;
    
    
    /** Creates new form MainFrame */
    public RobotGUI() {
        initComponents();
        setTitle("SABiR User Interface");
        
        render = new Renderer();
        robotDisplay.addGLEventListener(render);
        robotDisplay.addMouseListener(render);
        robotDisplay.addMouseMotionListener(render);
        robotDisplay.addKeyListener(render);
        
        animator = new Animator(robotDisplay);

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                // Run this on another thread than the AWT event queue to
                // make sure the call to Animator.stop() completes before
                // exiting
                new Thread(new Runnable() {

                    public void run() {
                        animator.stop();
                        System.exit(0);
                    }
                }).start();
            }
        });
        animator.start();
    }

    @Override
    public void setVisible(boolean show){
        if(!show)
            animator.stop();
        super.setVisible(show);
        if(!show)
            animator.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connect = new JButton();
        initialize = new JButton();
        pause = new JButton();
        stop = new JButton();
        extract = new JButton();
        header = new JLabel();
        messageCenterLabel = new JLabel();
        jScrollPane1 = new JScrollPane();
        messageCenter = new JTextArea();
        decrAngleA = new JButton();
        incrAngleA = new JButton();
        angleA = new JLabel();
        decrAngleB = new JButton();
        incrAngleB = new JButton();
        angleB = new JLabel();
        execOr = new JButton();
        cancelOr = new JButton();
        currentAngleOrALabel = new JLabel();
        currentAngleOrBLabel = new JLabel();
        currentAngleAOr = new JLabel();
        currentAngleBOr = new JLabel();
        depthIncrFull = new JButton();
        depthIncrPart = new JButton();
        depthDecrPart = new JButton();
        depthDecrFull = new JButton();
        depthLabel = new JLabel();
        insert = new JButton();
        insertCancel = new JButton();
        posVectorLabel = new JLabel();
        dirVectorLabel = new JLabel();
        posX = new JTextField();
        posY = new JTextField();
        posZ = new JTextField();
        dirX = new JTextField();
        dirY = new JTextField();
        dirZ = new JTextField();
        move = new JButton();
        selectPath = new JButton();
        robotDisplay = new GLCanvas();
        
        setAngles = new JButton();
        i = new JTextField();
        angles = new JLabel();
        value = new JLabel();
        v = new JTextField();
        
        
        robotDisplay.setBackground(Color.white);
        

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        connect.setText("Connect");
        connect.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        initialize.setText("Initialize");
        initialize.setEnabled(false);
        initialize.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                initializeActionPerformed(evt);
            }
        });

        pause.setText("Pause");
        pause.setEnabled(false);
        pause.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        stop.setText("STOP");
        stop.setEnabled(false);
        stop.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        extract.setText("Extract");
        extract.setEnabled(false);
        extract.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                extractActionPerformed(evt);
            }
        });

        header.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        header.setText("SABiR CONTROL");

        messageCenterLabel.setFont(new Font("Tahoma", 1, 14));
        messageCenterLabel.setText("Message Center:");

        messageCenter.setColumns(20);
        messageCenter.setRows(5);
        jScrollPane1.setViewportView(messageCenter);

        decrAngleA.setText(" - ");
        decrAngleA.setEnabled(false);
        decrAngleA.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                decrAngleAActionPerformed(evt);
            }
        });

        incrAngleA.setText(" + ");
        incrAngleA.setEnabled(false);
        incrAngleA.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                incrAngleAActionPerformed(evt);
            }
        });

        angleA.setText("---");

        decrAngleB.setText(" - ");
        decrAngleB.setEnabled(false);
        decrAngleB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                decrAngleBActionPerformed(evt);
            }
        });

        incrAngleB.setText(" + ");
        incrAngleB.setEnabled(false);
        incrAngleB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                incrAngleBActionPerformed(evt);
            }
        });

        angleB.setText("---");

        execOr.setText("Execute Orientation");
        execOr.setEnabled(false);
        execOr.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                execOrActionPerformed(evt);
            }
        });

        cancelOr.setText("Cancel");
        cancelOr.setEnabled(false);
        cancelOr.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelOrActionPerformed(evt);
            }
        });
        
        
        //added!!!! 
        setAngles.setText("set Angles");
        setAngles.setEnabled(false);
        setAngles.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		setAnglesActionPerformed(evt);
        	}
        });

        angles.setText("Angle: ");
        value.setText(" = ");

        
        
        
        
        currentAngleOrALabel.setText("Current Angular Orientation :");

        currentAngleOrBLabel.setText("Current Angular Orientation :");

        currentAngleAOr.setText("0.0°");

        currentAngleBOr.setText("0.0°");

        depthIncrFull.setText("+");
        depthIncrFull.setEnabled(false);
        depthIncrFull.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depthIncrFullActionPerformed(evt);
            }
        });

        depthIncrPart.setText("+");
        depthIncrPart.setEnabled(false);
        depthIncrPart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depthIncrPartActionPerformed(evt);
            }
        });

        depthDecrPart.setText("-");
        depthDecrPart.setEnabled(false);
        depthDecrPart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depthDecrPartActionPerformed(evt);
            }
        });

        depthDecrFull.setText("-");
        depthDecrFull.setEnabled(false);
        depthDecrFull.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depthDecrFullActionPerformed(evt);
            }
        });

        depthLabel.setText("---");

        insert.setText("Insert");
        insert.setEnabled(false);
        insert.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        insertCancel.setText("Cancel");
        insertCancel.setEnabled(false);
        insertCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                insertCancelActionPerformed(evt);
            }
        });

        posVectorLabel.setText("Position Vector");

        dirVectorLabel.setText("Direction Vector");

        move.setText("Move");
        move.setEnabled(false);
        move.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });

        selectPath.setText("Select Path");
        selectPath.setEnabled(false);
        selectPath.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                selectPathActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                                    .addComponent(connect, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(initialize, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pause, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stop, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(extract, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectPath, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                    .addComponent(messageCenterLabel)
                                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                            .addComponent(robotDisplay, GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                    .addComponent(depthDecrFull)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(depthLabel)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                                    .addComponent(depthDecrPart)
                                    .addComponent(depthIncrPart))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                                    .addComponent(insert, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(insertCancel)))
                            .addComponent(depthIncrFull)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(decrAngleA)
                                        .addPreferredGap(ComponentPlacement.RELATED)
                                        .addComponent(angleA))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(decrAngleB)
                                        .addPreferredGap(ComponentPlacement.RELATED)
                                        .addComponent(angleB)))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(incrAngleA)
                                        .addPreferredGap(ComponentPlacement.UNRELATED)
                                        .addComponent(currentAngleOrALabel)
                                        .addPreferredGap(ComponentPlacement.UNRELATED)
                                        .addComponent(currentAngleAOr))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(incrAngleB)
                                        .addPreferredGap(ComponentPlacement.UNRELATED)
                                        .addComponent(currentAngleOrBLabel)
                                        .addPreferredGap(ComponentPlacement.UNRELATED)
                                        .addComponent(currentAngleBOr))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(execOr)
                                .addGap(45, 45, 45)
                                .addComponent(cancelOr))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(posVectorLabel)
                            .addComponent(dirVectorLabel))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                            .addComponent(posX)
                            .addComponent(dirX, GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                            .addComponent(posY)
                            .addComponent(dirY, GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(posZ, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addComponent(move))
                            .addComponent(dirZ, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE))))
                .addGap(131, 131, 131))
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(header, GroupLayout.PREFERRED_SIZE, 313, GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(header)
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                    .addComponent(decrAngleA)
                                    .addComponent(incrAngleA)
                                    .addComponent(angleA)
                                    .addComponent(currentAngleOrALabel)
                                    .addComponent(currentAngleAOr))
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(decrAngleB)
                                        .addComponent(angleB)
                                        .addComponent(incrAngleB))
                                    .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(currentAngleOrBLabel)
                                        .addComponent(currentAngleBOr)))
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                    .addComponent(execOr)
                                    .addComponent(cancelOr)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(messageCenterLabel)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(connect)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(initialize)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(pause)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(stop)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(extract)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(selectPath)))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(robotDisplay, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(posVectorLabel)
                            .addComponent(posX, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(posY, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(posZ, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(move))
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(dirVectorLabel)
                            .addComponent(dirX, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(dirY, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(dirZ, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(depthIncrPart)
                            .addComponent(insert))
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                            .addComponent(depthDecrPart)
                            .addComponent(insertCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(depthIncrFull)
                        .addGap(31, 31, 31)
                        .addComponent(depthLabel)
                        .addGap(18, 18, 18)
                        .addComponent(depthDecrFull)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectActionPerformed(ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
         initialize.setEnabled(true);

        try {
            matlabcontrol.RemoteMatlabProxyFactory factory = new matlabcontrol.RemoteMatlabProxyFactory();
            this.proxy = factory.getProxy();
        } catch (MatlabConnectionException ex) {
            Logger.getLogger(RobotGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        delegator = new Delegator();
		delegator.GuiRegister(this);
        connect.setEnabled(false);
    }//GEN-LAST:event_connectActionPerformed

    private void initializeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_initializeActionPerformed
        angleA.setText(Double.toString(render.getAngles(0)));
        angleB.setText(Double.toString(render.getAngles(1)));
        currentAngleAOr.setText("0.0°");
        incrAngleA.setEnabled(true);
        decrAngleA.setEnabled(true);
        depthIncrFull.setEnabled(true);
        depthDecrFull.setEnabled(true);
        depthIncrPart.setEnabled(true);
        depthDecrPart.setEnabled(true);
        insert.setEnabled(true);
        insertCancel.setEnabled(true);
        incrAngleB.setEnabled(true);
        decrAngleB.setEnabled(true);
        pause.setEnabled(true);
        stop.setEnabled(true);
        extract.setEnabled(true);
        move.setEnabled(true);
        execOr.setEnabled(true);
        cancelOr.setEnabled(true);
        selectPath.setEnabled(true);
        cancelOrAVal = 0;
        cancelOrBVal = 0;
    }//GEN-LAST:event_initializeActionPerformed

    private void pauseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseActionPerformed

    private void stopActionPerformed(ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopActionPerformed

    private void extractActionPerformed(ActionEvent evt) {//GEN-FIRST:event_extractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extractActionPerformed

    private void incrAngleAActionPerformed(ActionEvent evt) {//GEN-FIRST:event_incrAngleAActionPerformed
        String s = angleA.getText();
        s = s.substring(0, s.length() - 1);
        double d = Double.parseDouble(s);
        d++;
        render.setAngles(0, d);
        angleA.setText(d + "°");
    }//GEN-LAST:event_incrAngleAActionPerformed
    
    private void decrAngleAActionPerformed(ActionEvent evt) {//GEN-FIRST:event_decrAngleAActionPerformed
    	String s = angleA.getText();
        s = s.substring(0, s.length() - 1);
        double d = Double.parseDouble(s);
        d--;
        render.setAngles(0, d);
        angleA.setText(d + "°");
    }//GEN-LAST:event_decrAngleAActionPerformed



    private void decrAngleBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_decrAngleBActionPerformed
        String s = angleB.getText();
        s = s.substring(0, s.length() - 1);
        double d = Double.parseDouble(s);
        d--;
        render.setAngles(1, d);
        angleB.setText(d + "°");
    }//GEN-LAST:event_decrAngleBActionPerformed

    private void incrAngleBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_incrAngleBActionPerformed
    /*try {
			if (proxy == null) {
				System.out.println("Warning proxy is null");
			}
			delegator.proxyRegister(proxy);
			delegator.handleInitialization();
		} catch (MatlabInvocationException e1) {
			// TODO Auto-generated catch block
			//_returnArea.setText("handleInitialization failed");
		}*/

        String s = angleB.getText();
        s = s.substring(0, s.length() - 1);
        double d = Double.parseDouble(s);
        d++;
        render.setAngles(1, d);
        angleB.setText(d + "°");
        
//        currentAngleOrALabel.setText("Angle[0] : " + render.getAngles(0) + "Angle[1] : " + render.getAngles(1) + "Angle[2] : " + render.getAngles(2));
  //      currentAngleOrBLabel.setText("Angle[3] : " + render.getAngles(3) + "Angle[4] : " + render.getAngles(4));

    }//GEN-LAST:event_incrAngleBActionPerformed

    private void execOrActionPerformed(ActionEvent evt) {//GEN-FIRST:event_execOrActionPerformed
        String s = angleB.getText();
        s = s.substring(0, s.length() - 1);
        double d = Double.parseDouble(s);
        s = currentAngleBOr.getText().substring(0, currentAngleAOr.getText().length() - 1);
        cancelOrBVal = Double.parseDouble(s);
        s = angleA.getText();
        s = s.substring(0, s.length() - 1);
        d = Double.parseDouble(s);
        s = currentAngleAOr.getText().substring(0, currentAngleAOr.getText().length() - 1);
        cancelOrBVal = Double.parseDouble(s);
        angleA.setText("0.0°");
        angleB.setText("0.0°");
        s = currentAngleAOr.getText();
        s = s.substring(0, s.length() - 1);
        d += Double.parseDouble(s);
        currentAngleAOr.setText(d + "°");
    }//GEN-LAST:event_execOrActionPerformed

    private void cancelOrActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelOrActionPerformed
        currentAngleAOr.setText(cancelOrAVal + "°");
        angleA.setText("0.0°");
        currentAngleBOr.setText(cancelOrBVal + "°");
        angleB.setText("0.0°");
    }//GEN-LAST:event_cancelOrActionPerformed

    private void depthIncrFullActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depthIncrFullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depthIncrFullActionPerformed

    private void depthIncrPartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depthIncrPartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depthIncrPartActionPerformed

    private void depthDecrPartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depthDecrPartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depthDecrPartActionPerformed

    private void depthDecrFullActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depthDecrFullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depthDecrFullActionPerformed

    private void insertActionPerformed(ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertActionPerformed

    private void insertCancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_insertCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertCancelActionPerformed

    private void moveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed
        delegator.handleMoveAction();
    }//GEN-LAST:event_moveActionPerformed

    private void selectPathActionPerformed(ActionEvent evt) {//GEN-FIRST:event_selectPathActionPerformed
        frame = new JFrame();
        GridLayout grid = new GridLayout(2, 2);
        frame.setLayout(grid);
        canvas1 = new GLCanvas();
        canvas2 = new GLCanvas();
        canvas3 = new GLCanvas();
        canvas4 = new GLCanvas();
        frame.add(canvas1);
        frame.add(canvas2);
        frame.add(canvas3);
        frame.add(canvas4);
        frame.setSize(640, 480);
        frame.setVisible(true);

    }
    
	private void setAnglesActionPerformed(ActionEvent evt) {
		int integer = Integer.parseInt(i.getText());
	    double value = Double.parseDouble(v.getText());
		render.setAngles(integer, value);
		// TODO Auto-generated method stub
	}
    //GEN-LAST:event_selectPathActionPerformed

    /**
     * Called from within initComponents().
     * hint: to customize the generated code choose 'Customize Code' in the contextmenu
     * of the selected UI Component you wish to cutomize in design mode.
     * @return Returns customized GLCapabilities.
     */
    private GLCapabilities createGLCapabilites() {
        
        GLCapabilities capabilities = new GLCapabilities();
        capabilities.setHardwareAccelerated(true);

        // try to enable 2x anti aliasing - should be supported on most hardware
        capabilities.setNumSamples(2);
        capabilities.setSampleBuffers(true);
        
        return capabilities;
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        // Run this in the AWT event thread to prevent deadlocks and race conditions
        EventQueue.invokeLater(new Runnable() {
            public void run() {

                // switch to system l&f for native font rendering etc.
                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }catch(Exception ex) {
                    Logger.getLogger(getClass().getName()).log(Level.INFO, "can not enable system look and feel", ex);
                }

                RobotGUI frame = new RobotGUI();
                frame.setBackground(Color.white);
                frame.setVisible(true);
            }
        });
    }


    
    // End of variables declaration//GEN-END:variables

    public void sendMessage(String string) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    public Vector getTargetDirection() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    public Vector getTargetPosition() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

}
